function New-XdrCloudAppsDiscoveryPolicy {
    <#
    .SYNOPSIS
        Creates a new Cloud Apps discovery policy.

    .DESCRIPTION
        Creates a new app discovery policy in Microsoft Defender for Cloud Apps.
        Discovery policies allow you to set alerts for when new apps are discovered
        or when usage thresholds are exceeded.

    .PARAMETER Name
        The name of the discovery policy. This parameter is required.

    .PARAMETER Description
        The description of the discovery policy.

    .PARAMETER AlertSeverity
        The severity level for alerts generated by this policy.
        Valid values are: LOW, MEDIUM, HIGH. Defaults to MEDIUM.

    .PARAMETER EnableAlerts
        When specified, enables alerting for this policy.

    .PARAMETER Enabled
        When specified, the policy is enabled. Defaults to $true.

    .PARAMETER ConsoleFilters
        Console filters as a JSON string.

    .PARAMETER Filters
        A hashtable containing the filter configuration for the policy.

    .PARAMETER Thresholds
        A hashtable containing threshold configuration. Supports keys:
        - totalBytes: Threshold for total bytes transferred
        - usersCount: Threshold for number of users

    .PARAMETER UseThresholds
        When specified, enables threshold-based alerting.

    .PARAMETER StreamIds
        Array of stream IDs to monitor for discovery.

    .PARAMETER AppCategories
        Array of app category IDs to filter on.

    .PARAMETER AppTags
        Array of app tags to filter on.

    .PARAMETER RiskScore
        Minimum risk score threshold.

    .EXAMPLE
        New-XdrCloudAppsDiscoveryPolicy -Name "New App Alert" -Description "Alert on new high-risk apps" -AlertSeverity HIGH -EnableAlerts

        Creates a new discovery policy that alerts on high-risk apps.

    .EXAMPLE
        $thresholds = @{ totalBytes = 1073741824; usersCount = 10 }
        New-XdrCloudAppsDiscoveryPolicy -Name "Usage Policy" -Thresholds $thresholds -UseThresholds -EnableAlerts

        Creates a discovery policy with byte and user count thresholds (1GB and 10 users).

    .EXAMPLE
        New-XdrCloudAppsDiscoveryPolicy -Name "Stream Monitor" -StreamIds @("stream1", "stream2") -Enabled

        Creates a discovery policy monitoring specific data streams.

    .NOTES
        Requires an active XDR session established via Connect-XdrByEstsCookie.
    #>
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSUseShouldProcessForStateChangingFunctions', '', Justification = 'Creating policy is the intended action')]
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [string]$Name,

        [Parameter()]
        [string]$Description,

        [Parameter()]
        [ValidateSet("LOW", "MEDIUM", "HIGH")]
        [string]$AlertSeverity = "MEDIUM",

        [Parameter()]
        [switch]$EnableAlerts,

        [Parameter()]
        [switch]$Enabled,

        [Parameter()]
        [string]$ConsoleFilters,

        [Parameter()]
        [hashtable]$Filters,

        [Parameter()]
        [hashtable]$Thresholds,

        [Parameter()]
        [switch]$UseThresholds,

        [Parameter()]
        [string[]]$StreamIds,

        [Parameter()]
        [int[]]$AppCategories,

        [Parameter()]
        [string[]]$AppTags,

        [Parameter()]
        [int]$RiskScore
    )

    begin {
        Update-XdrConnectionSettings
        $Uri = "https://security.microsoft.com/apiproxy/mcas/cas/api/v1/policy/discovery/"
    }

    process {
        Write-Verbose "Creating new Cloud Apps discovery policy: $Name"

        # Default Enabled to true if not explicitly specified
        $enabledValue = if ($PSBoundParameters.ContainsKey('Enabled')) { $Enabled.IsPresent } else { $true }

        $body = @{
            name          = $Name
            policyType    = "DISCOVERY"
            severity      = $AlertSeverity
            alertsEnabled = $EnableAlerts.IsPresent
            enabled       = $enabledValue
        }

        if ($PSBoundParameters.ContainsKey('Description')) {
            $body['description'] = $Description
        }

        if ($PSBoundParameters.ContainsKey('ConsoleFilters')) {
            $body['consoleFilters'] = $ConsoleFilters
        }

        if ($PSBoundParameters.ContainsKey('Filters')) {
            $body['filters'] = $Filters
        }

        if ($PSBoundParameters.ContainsKey('Thresholds')) {
            $body['thresholds'] = $Thresholds
        }

        if ($UseThresholds.IsPresent) {
            $body['useThresholds'] = $true
        }

        if ($PSBoundParameters.ContainsKey('StreamIds')) {
            $body['streamIds'] = $StreamIds
        }

        if ($PSBoundParameters.ContainsKey('AppCategories')) {
            $body['appCategories'] = $AppCategories
        }

        if ($PSBoundParameters.ContainsKey('AppTags')) {
            $body['appTags'] = $AppTags
        }

        if ($PSBoundParameters.ContainsKey('RiskScore')) {
            $body['riskScore'] = $RiskScore
        }

        $jsonBody = $body | ConvertTo-Json -Depth 10

        Write-Verbose "Request body: $jsonBody"

        try {
            $result = Invoke-RestMethod -Uri $Uri -Method Post -Body $jsonBody -ContentType "application/json" -WebSession $script:session -Headers $script:headers
            Write-Verbose "Successfully created discovery policy: $Name"
            return $result
        }
        catch {
            Write-Error "Failed to create discovery policy '$Name': $_"
            throw
        }
    }
}
