function New-XdrCloudAppsFilePolicy {
    <#
    .SYNOPSIS
        Creates a new Cloud Apps file policy.

    .DESCRIPTION
        Creates a new file policy in Microsoft Defender for Cloud Apps.
        File policies allow you to monitor and protect files across your cloud apps.

    .PARAMETER Name
        The name of the file policy. This parameter is required.

    .PARAMETER Description
        The description of the file policy.

    .PARAMETER AlertSeverity
        The severity level for alerts generated by this policy.
        Valid values are: LOW, MEDIUM, HIGH

    .PARAMETER EnableAlerts
        When specified, enables alerting for this policy.

    .PARAMETER Enabled
        When specified, the policy is enabled. Defaults to $true.

    .PARAMETER ConsoleFilters
        Console filters as a JSON string.

    .PARAMETER Filters
        A hashtable containing the filter configuration for the policy.

    .PARAMETER PolicyType
        The type of file policy. Defaults to "FILE".

    .PARAMETER AppId
        Array of application IDs to apply the policy to.

    .PARAMETER FileExtension
        Array of file extensions to filter on.

    .PARAMETER FileSharingOption
        File sharing option filter.

    .EXAMPLE
        New-XdrCloudAppsFilePolicy -Name "Sensitive Data Policy" -Description "Monitor sensitive files" -AlertSeverity HIGH -EnableAlerts

        Creates a new file policy named "Sensitive Data Policy" with HIGH severity alerts enabled.

    .EXAMPLE
        $filters = @{ fileType = @{ eq = @(1, 2) } }
        New-XdrCloudAppsFilePolicy -Name "Document Policy" -Filters $filters -Enabled

        Creates a new enabled file policy with custom filters.

    .NOTES
        Requires an active XDR session established via Connect-XdrByEstsCookie.
    #>
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSUseShouldProcessForStateChangingFunctions', '', Justification = 'Creating policy is the intended action')]
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [string]$Name,

        [Parameter()]
        [string]$Description,

        [Parameter()]
        [ValidateSet("LOW", "MEDIUM", "HIGH")]
        [string]$AlertSeverity = "MEDIUM",

        [Parameter()]
        [switch]$EnableAlerts,

        [Parameter()]
        [switch]$Enabled,

        [Parameter()]
        [string]$ConsoleFilters,

        [Parameter()]
        [hashtable]$Filters,

        [Parameter()]
        [string]$PolicyType = "FILE",

        [Parameter()]
        [int[]]$AppId,

        [Parameter()]
        [string[]]$FileExtension,

        [Parameter()]
        [string]$FileSharingOption
    )

    begin {
        Update-XdrConnectionSettings
        $Uri = "https://security.microsoft.com/apiproxy/mcas/cas/api/v1/policy/file/"
    }

    process {
        Write-Verbose "Creating new Cloud Apps file policy: $Name"

        # Default Enabled to true if not explicitly specified
        $enabledValue = if ($PSBoundParameters.ContainsKey('Enabled')) { $Enabled.IsPresent } else { $true }

        $body = @{
            name          = $Name
            policyType    = $PolicyType
            severity      = $AlertSeverity
            alertsEnabled = $EnableAlerts.IsPresent
            enabled       = $enabledValue
        }

        if ($PSBoundParameters.ContainsKey('Description')) {
            $body['description'] = $Description
        }

        if ($PSBoundParameters.ContainsKey('ConsoleFilters')) {
            $body['consoleFilters'] = $ConsoleFilters
        }

        if ($PSBoundParameters.ContainsKey('Filters')) {
            $body['filters'] = $Filters
        }

        if ($PSBoundParameters.ContainsKey('AppId')) {
            $body['appId'] = $AppId
        }

        if ($PSBoundParameters.ContainsKey('FileExtension')) {
            $body['fileExtension'] = $FileExtension
        }

        if ($PSBoundParameters.ContainsKey('FileSharingOption')) {
            $body['fileSharingOption'] = $FileSharingOption
        }

        $jsonBody = $body | ConvertTo-Json -Depth 10

        Write-Verbose "Request body: $jsonBody"

        try {
            $result = Invoke-RestMethod -Uri $Uri -Method Post -Body $jsonBody -ContentType "application/json" -WebSession $script:session -Headers $script:headers
            Write-Verbose "Successfully created file policy: $Name"
            return $result
        }
        catch {
            Write-Error "Failed to create file policy '$Name': $_"
            throw
        }
    }
}
