function Set-XdrCloudAppsPolicy {
    <#
    .SYNOPSIS
        Updates a policy in Microsoft Defender for Cloud Apps.

    .DESCRIPTION
        The Set-XdrCloudAppsPolicy cmdlet updates policies in Microsoft Defender for Cloud Apps.
        Use -Type to specify the policy type (File, OAuth). Use -Enabled to enable or disable
        a policy. Additional parameters allow updating policy properties like name, description,
        and alert settings.

        When only -Enabled is specified, the cmdlet uses the dedicated enable/disable endpoints.
        When other parameters are specified, the cmdlet uses the update endpoint.

    .PARAMETER Type
        The type of policy to update. Valid values are:
        - File: File policies for data protection
        - OAuth: OAuth app policies for third-party app governance

    .PARAMETER PolicyId
        The unique identifier of the policy to update.

    .PARAMETER Enabled
        When specified as $true, enables the policy. When $false, disables it.
        If this is the only change, uses the dedicated enable/disable endpoint.

    .PARAMETER Name
        The new name for the policy. Only applicable to File policies.

    .PARAMETER Description
        The new description for the policy. Only applicable to File policies.

    .PARAMETER AlertSeverity
        The severity level for alerts generated by this policy.
        Valid values are: LOW, MEDIUM, HIGH. Only applicable to File policies.

    .PARAMETER EnableAlerts
        When specified as $true, enables alerting. When $false, disables alerting.
        Only applicable to File policies.

    .PARAMETER ConsoleFilters
        Console filters as a JSON string. Only applicable to File policies.

    .PARAMETER Filters
        A hashtable containing the filter configuration for the policy.
        Only applicable to File policies.

    .PARAMETER AppId
        Array of application IDs to apply the policy to. Only applicable to File policies.

    .PARAMETER FileExtension
        Array of file extensions to filter on. Only applicable to File policies.

    .PARAMETER FileSharingOption
        File sharing option filter. Only applicable to File policies.

    .PARAMETER WhatIf
        Shows what would happen if the cmdlet runs. The cmdlet does not run.

    .PARAMETER Confirm
        Prompts you for confirmation before running the cmdlet.

    .EXAMPLE
        Set-XdrCloudAppsPolicy -Type File -PolicyId "abc123" -Enabled $true

        Enables the specified file policy.

    .EXAMPLE
        Set-XdrCloudAppsPolicy -Type File -PolicyId "abc123" -Enabled $false

        Disables the specified file policy.

    .EXAMPLE
        Set-XdrCloudAppsPolicy -Type OAuth -PolicyId "def456" -Enabled $true

        Enables the specified OAuth policy.

    .EXAMPLE
        Set-XdrCloudAppsPolicy -Type File -PolicyId "abc123" -Name "Updated Policy Name"

        Updates the name of the specified file policy.

    .EXAMPLE
        Set-XdrCloudAppsPolicy -Type File -PolicyId "abc123" -AlertSeverity HIGH -EnableAlerts $true

        Updates the alert severity and enables alerts for the specified file policy.

    .EXAMPLE
        Get-XdrCloudAppsPolicy -Type File -PolicyId "abc123" | Set-XdrCloudAppsPolicy -Type File -Enabled $false

        Disables the specified file policy using pipeline input.

    .NOTES
        Requires an active XDR session established via Connect-XdrByEstsCookie.
    #>
    [OutputType([PSCustomObject])]
    [CmdletBinding(SupportsShouldProcess)]
    param (
        [Parameter(Mandatory = $true)]
        [ValidateSet("File", "OAuth")]
        [string]$Type,

        [Parameter(Mandatory = $true, ValueFromPipelineByPropertyName = $true)]
        [Alias('_id')]
        [ValidateNotNullOrEmpty()]
        [string]$PolicyId,

        [Parameter()]
        [bool]$Enabled,

        [Parameter()]
        [string]$Name,

        [Parameter()]
        [string]$Description,

        [Parameter()]
        [ValidateSet("LOW", "MEDIUM", "HIGH")]
        [string]$AlertSeverity,

        [Parameter()]
        [bool]$EnableAlerts,

        [Parameter()]
        [string]$ConsoleFilters,

        [Parameter()]
        [hashtable]$Filters,

        [Parameter()]
        [int[]]$AppId,

        [Parameter()]
        [string[]]$FileExtension,

        [Parameter()]
        [string]$FileSharingOption
    )

    begin {
        Update-XdrConnectionSettings
    }

    process {
        # Determine if this is an enable/disable only operation
        $enableDisableOnly = $PSBoundParameters.ContainsKey('Enabled') -and
            -not $PSBoundParameters.ContainsKey('Name') -and
            -not $PSBoundParameters.ContainsKey('Description') -and
            -not $PSBoundParameters.ContainsKey('AlertSeverity') -and
            -not $PSBoundParameters.ContainsKey('EnableAlerts') -and
            -not $PSBoundParameters.ContainsKey('ConsoleFilters') -and
            -not $PSBoundParameters.ContainsKey('Filters') -and
            -not $PSBoundParameters.ContainsKey('AppId') -and
            -not $PSBoundParameters.ContainsKey('FileExtension') -and
            -not $PSBoundParameters.ContainsKey('FileSharingOption')

        if ($enableDisableOnly) {
            # Use dedicated enable/disable endpoint
            $action = if ($Enabled) { "enable" } else { "disable" }
            $Uri = "https://security.microsoft.com/apiproxy/mcas/cas/api/v1/policies/$PolicyId/$action/"
            $statusText = if ($Enabled) { "Enabled" } else { "Disabled" }

            $actionVerb = if ($Enabled) { "Enabling" } else { "Disabling" }
            Write-Verbose "$actionVerb $Type policy: $PolicyId"

            if ($PSCmdlet.ShouldProcess($PolicyId, "$actionVerb $Type policy")) {
                try {
                    $result = Invoke-RestMethod -Uri $Uri -Method Post -ContentType "application/json" -WebSession $script:session -Headers $script:headers
                    Write-Verbose "Successfully $($statusText.ToLower()) policy: $PolicyId"

                    if ($result) {
                        return $result
                    } else {
                        return [PSCustomObject]@{
                            PolicyId = $PolicyId
                            Type     = $Type
                            Status   = $statusText
                            Success  = $true
                        }
                    }
                } catch {
                    Write-Error "Failed to $($action) $Type policy '$PolicyId': $_"
                    throw
                }
            }
        } else {
            # Use update endpoint (File policies only for now)
            if ($Type -ne "File") {
                Write-Error "Property updates are only supported for File policies. Use -Enabled to enable/disable OAuth policies."
                return
            }

            $Uri = "https://security.microsoft.com/apiproxy/mcas/cas/api/v1/policy/file/$PolicyId/"

            Write-Verbose "Updating $Type policy: $PolicyId"

            $body = @{}

            if ($PSBoundParameters.ContainsKey('Name')) {
                $body['name'] = $Name
            }

            if ($PSBoundParameters.ContainsKey('Description')) {
                $body['description'] = $Description
            }

            if ($PSBoundParameters.ContainsKey('AlertSeverity')) {
                $body['severity'] = $AlertSeverity
            }

            if ($PSBoundParameters.ContainsKey('EnableAlerts')) {
                $body['alertsEnabled'] = $EnableAlerts
            }

            if ($PSBoundParameters.ContainsKey('Enabled')) {
                $body['enabled'] = $Enabled
            }

            if ($PSBoundParameters.ContainsKey('ConsoleFilters')) {
                $body['consoleFilters'] = $ConsoleFilters
            }

            if ($PSBoundParameters.ContainsKey('Filters')) {
                $body['filters'] = $Filters
            }

            if ($PSBoundParameters.ContainsKey('AppId')) {
                $body['appId'] = $AppId
            }

            if ($PSBoundParameters.ContainsKey('FileExtension')) {
                $body['fileExtension'] = $FileExtension
            }

            if ($PSBoundParameters.ContainsKey('FileSharingOption')) {
                $body['fileSharingOption'] = $FileSharingOption
            }

            if ($body.Count -eq 0) {
                Write-Warning "No parameters specified to update. Please provide at least one parameter to modify."
                return
            }

            $jsonBody = $body | ConvertTo-Json -Depth 10

            Write-Verbose "Request body: $jsonBody"

            if ($PSCmdlet.ShouldProcess($PolicyId, "Update $Type policy")) {
                try {
                    $result = Invoke-RestMethod -Uri $Uri -Method Put -Body $jsonBody -ContentType "application/json" -WebSession $script:session -Headers $script:headers
                    Write-Verbose "Successfully updated $Type policy: $PolicyId"
                    return $result
                } catch {
                    Write-Error "Failed to update $Type policy '$PolicyId': $_"
                    throw
                }
            }
        }
    }

    end {
    }
}
